messages:
  commands:
    dont: '&cYou dont have permission for use that command!'

  events:
    kicked: '&1&lYou &fwas kicked by &a[ &e&lBowExploitFixer by &a&lArtik &cand &b&lL1te &a]'
    warn: '&0&kAAAAA &c&l[PROTECTION] &6&nIf you will use BowExploit, we will have to kick you! &0&kAAAAA'
